spring.application.name=credit-policy-engine


spring.datasource.url=jdbc:h2:file:./data/policy-engine
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=credit
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2
